AWS Elasticsearch Service support for curator
cloudfoundry-community/logsearch-boshrelease pull request #109
Opened 2017-11-28 23:21 UTC by kitsirota

Hi,

This PR adds the ability to set host and SSL parameters to enable operators to deploy a subset of this release with the parser, router and curator while shipping all the logs to AWS Elasticsearch Service. I started rolling out this out for cerebro, but I'll submit those changes in a separate PR.

For context: In our deployment, we have a CF deployment on AWS and we prefer shipping our logs to AWS Elasticsearch Service instead of running elasticsearch as part of the bosh release.

I'd be happy to iterate on this or answer any questions that come up.

Thanks!
Kit

2017-12-05 16:32 UTC, Infra-Red commented on jobs/curator/templates/config/config.yml.erb
> +  logfile: '/var/vcap/sys/log/curator/curator.stdout.log'
This line should be empty since we're redirecting all output to STDOUT in run script.

2017-12-05 16:35 UTC, Infra-Red commented on jobs/curator/templates/config/config.yml.erb
> +  use_ssl: <%= elasticsearch_use_ssl %>
Property can be accessible directly, smth like `use_ssl: <% p("curator.elasticsearch.use_ssl", "False") %>` should work here.

2017-12-05 16:36 UTC, Infra-Red requested changes
Hi @kitsirota ! Thanks PR, please review the comments.

2018-10-25 13:27 UTC, axelaris commented
Closing PR since no feedback from author for a long period of time.

2018-10-25 13:27 UTC, closed without merging