Added variabes into stub to ease automated filling
cloudfoundry-community/logsearch-boshrelease pull request #23
Opened 2017-01-11 14:51 UTC by axelaris

Using these variables it will be easier to create manifests even without any manual editing

2017-01-11 14:54 UTC, Infra-Red reviewed
@axelaris  Could you please apply this changes for other stubs too.

2017-01-11 15:07 UTC, hannayurkevich requested changes
Please make the same changes in other stubs. And also add security groups description to the deploy deoc.

2017-01-11 15:07 UTC, hannayurkevich commented on templates/stub.openstack.example.yml
> +    - bosh
Please mention the sg in the deploy doc.

2017-01-11 15:07 UTC, hannayurkevich commented on templates/stub.openstack.example.yml
> +    - logsearch
Please mention the sg in the deploy doc.

2017-01-12 13:23 UTC, axelaris commented on templates/stub.openstack.example.yml
> +    - bosh
done

2017-01-12 13:24 UTC, axelaris commented on templates/stub.openstack.example.yml
> +    - logsearch
done

2017-01-12 13:38 UTC, merged

2017-01-12 13:38 UTC, hannayurkevich commented
Thanks, @axelaris!