Use logstash redis defaults.
cloudfoundry-community/logsearch-boshrelease pull request #25
Opened 2017-01-17 21:02 UTC by jmcarp

[Resolves #24]

Most of the diffs here are changing tabs to spaces. The only meaningful change is dropping the default redis congestion properties, then only adding them to the redis options if defined.

2017-01-17 21:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cloudfoundry-community/logsearch-boshrelease?pullRequest=25) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cloudfoundry-community/logsearch-boshrelease?pullRequest=25) before we can accept your contribution.<br/>

2017-01-17 21:08 UTC, rogeruiz commented on jobs/ingestor_syslog/templates/config/logstash.conf.erb
> +        %>
72 to 87 are the changes introduced in this PR. Most of the rest is whitespace.

2017-01-18 09:32 UTC, Infra-Red requested changes
Hi @jmcarp, everything looks fine, but could you please update redis-input-plugin for parser logstash instances to also use the ELK default settings.

2017-01-18 15:38 UTC, jmcarp commented
The only non-default option I saw for redis input was `threads`, which I moved into the generic `options` hash, which I updated to be merged into the individually defined options. Let me know if I missed anything else!

2017-01-18 15:50 UTC, Infra-Red approved these changes

2017-01-18 15:51 UTC, Infra-Red commented
LGTM

2017-01-18 15:51 UTC, merged