Make SSL optional when cert is set for ingestor and kibana
cloudfoundry-community/logsearch-boshrelease pull request #43
Opened 2017-02-24 09:59 UTC by janaurka

This introduces `properties.haproxy.kibana.enable_ssl` and
`properties.haproxy.ingestor.enable_ssl` (both defaults to false)
which take care of enable SSL on the haproxy more flexible then
before.

Previously if a SSL cert was given, port `5514` (ingestor) and
kibana, port 80 (HTTP) or 443 (HTTPS) was automatically enabled.

With this commit, one can be enabled when the other is disabled.

Example:
Ingestor (syslog) traffic should be plainext, but the
Kibana traffic should be encrypted.

2017-02-24 10:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cloudfoundry-community/logsearch-boshrelease?pullRequest=43) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cloudfoundry-community/logsearch-boshrelease?pullRequest=43) before we can accept your contribution.<br/><hr/>**Jan Mueller** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cloudfoundry-community/logsearch-boshrelease?pullRequest=43) it.</sub>

2017-02-27 12:32 UTC, Infra-Red requested changes

2017-02-27 12:32 UTC, Infra-Red commented on jobs/haproxy/templates/haproxy.config.erb
> +    <% if properties.haproxy.ssl_pem and properties.haproxy.elastic.enable_ssl == true %>
This property is missing in haproxy job spec.

2017-03-01 10:50 UTC, janaurka commented
@Infra-Red: You are right, should be fixed with 7ab1ecb.

2017-03-03 09:25 UTC, Infra-Red requested changes

2017-03-03 09:25 UTC, Infra-Red commented on jobs/haproxy/spec
> +    description: "Enable or Disable SSL for for syslog/ingestor traffic on haproxy"
@janaurka Could you please also update property description?

2017-04-03 08:54 UTC, janaurka commented
@Infra-Red: sorry, this somehow went unnoticed. Should be fixed now.

2017-04-06 21:12 UTC, Infra-Red approved these changes

2017-04-06 21:12 UTC, merged