Allow custom logstash plugins.
cloudfoundry-community/logsearch-boshrelease pull request #5
Opened 2016-11-15 21:15 UTC by jmcarp

This uses a format that's slightly different from the one used for elastic and kibana plugins, but it's useful to be able to specify arbitrary arguments to the installer like `--version`. WDYT?

2017-01-04 16:00 UTC, axelaris commented
Hi @jmcarp and happy New Year!
What's the status of signing CLA from your side? Did our lawyers had a chance to talk?

2017-01-04 16:08 UTC, mogul commented
Hi @axelaris, and happy new year to you too! 

From David Schachner at Pivotal on 12/21/2016: 

> Apologies for the delayed response. Work is already underway to revise the CLA so that it accounts for the public domain use case you've raised.
> 
> In the meantime while this effort is underway, we can advise our project teams to accept your pull requests without CLA acceptance as long as you clearly mark your contributions with a public domain dedication.
> 
> Thanks again for bringing this issue to our attention!

Can you perhaps check with him to confirm?

2017-01-04 16:12 UTC, mogul commented
Sorry, I had your CLA confused with Pivotal's. I'll check!

2017-01-16 21:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cloudfoundry-community/logsearch-boshrelease?pullRequest=5) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cloudfoundry-community/logsearch-boshrelease?pullRequest=5) before we can accept your contribution.<br/>

2017-01-16 21:46 UTC, jmcarp commented
Merge conflicts resolved.

2017-01-18 17:07 UTC, jmcarp commented
@Infra-Red: can I trouble you to take a look at this when you have time? Looking forward to building this release from upstream and not from our fork 😄

2017-01-18 17:16 UTC, Infra-Red requested changes

2017-01-18 17:16 UTC, Infra-Red commented on jobs/ingestor_syslog/spec
> -
@jmcarp Overall it looks good, but could you add this part back, I think that they are lost during sync with upstream.

2017-01-18 17:34 UTC, jmcarp commented
Thanks for catching that mistake, just reverted it.

2017-01-18 17:45 UTC, Infra-Red commented
LGTM after fixing. Thanks @jmcarp

2017-01-18 17:45 UTC, merged