Drop default cerebro secret.
cloudfoundry-community/logsearch-boshrelease pull request #85
Opened 2017-07-14 20:46 UTC by jmcarp

Let's require operators who want cerebro to set a non-default secret instead of recommending it in a comment 😃

2017-07-14 20:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cloudfoundry-community/logsearch-boshrelease?pullRequest=85) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cloudfoundry-community/logsearch-boshrelease?pullRequest=85) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cloudfoundry-community/logsearch-boshrelease?pullRequest=85) it.</sub>

2017-07-21 15:54 UTC, jmcarp commented
It looks like logstash tests failed on this build, but I'm not sure why changing cerebro properties would matter for those. WDYT @Infra-Red?

2017-07-22 19:39 UTC, Infra-Red requested changes
Fixed failing tests in https://github.com/cloudfoundry-community/logsearch-boshrelease/commit/db75087fdf38d8e52d2b446647f9841fbd35f94f. Ready to merge after adding the property to deployment manifests.

2017-07-24 04:13 UTC, jmcarp commented
Thanks, updated @Infra-Red .

2017-07-24 06:19 UTC, Infra-Red approved these changes

2017-07-24 06:19 UTC, merged